name: Scala CI

on:
  pull_request:
    branches: [ releases/** ]
  push:
    branches: [ releases/** ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Cache SBT
      uses: actions/cache@v2
      with:
        path: | 
          ~/.ivy2/cache
          ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/Dependencies.scala') }}-${{ hashFiles('**/build.sbt') }}

    - name: Compile
      run: sbt clean compile

    - name: Run tests
      run: sbt test

    - name: Setup authentication for Sonatype
      if: github.event_name == 'push'
      env:
        SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      run: |
        CREDENTIALS_FILE=/home/runner/.sbt/credentials
        mkdir -p /home/runner/.sbt/1.0/
        touch $CREDENTIALS_FILE
        echo "realm=Sonatype Nexus Repository Manager" >> $CREDENTIALS_FILE
        echo "host=s01.oss.sonatype.org" >> $CREDENTIALS_FILE
        echo "user=$SONATYPE_USER" >> $CREDENTIALS_FILE
        echo "password=$SONATYPE_PASSWORD" >> $CREDENTIALS_FILE
        touch /home/runner/.sbt/1.0/sonatype.sbt
        echo 'credentials += Credentials(Path.userHome / ".sbt" / "credentials")' >> /home/runner/.sbt/1.0/sonatype.sbt

    - name: Publish
      if: github.event_name == 'push'
      run: sbt publish
