name: Compile the code and run tests
on: push
jobs:
  compile_and_testing:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11
      - name: Compile
        run: sbt compile
      - name: Run tests
        run: sbt test