name: Compile the code
on: push
jobs:
  compile_code:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: List files
        run: |
          pwd
          ls